### ISSUE TITLE
Live Duo

### ISSUE THREAD

**Issue by ffloress** [KL-Yang/mbl-linux-4.0#1]
Hello, I want too a clean minimal debian on my live duo.
Can I use your image?
Just clone it to 1 hd, start the server, and add the second hdd later?

I am learning things like DD recently...

**Comment by KL-Yang** [comment]
I don't have a duo, so it's not tested, if you can install a UART to your duo like
http://mybookworld.wikidot.com/wd-mybook-live-duo-uart
Maybe you can try the new kernel, otherwise it might be quite risky.
Not sure if the sata and usb will work properly or not.

**Comment by ffloress** [comment]
Do I need this UART trick , or is it just if I want to use the newest kernel?

I would like only to start with a minimal linux, so I can ssh into into, install torrent client and that is it. I dont want the WD stuff.... Is it possible, to just install a linux on a hd, and start fresH? Or Do I need to use this UART cable?

**Comment by KL-Yang** [comment]
You can follow this instruction to install a minimum debian squeeze that work with original kernel. (But thing might go wrong, and then you may need to disassemble the hard drive or install the cable to make it right, DO BACKUP EVERYTHING)
https://www.schwabenlan.de/en/linux/clean-debian-install-on-mybook-live-nas
newer debian might not work well with stock kernel, too old.

**Comment by ffloress** [comment]
I See..
What I dont understand is.. Do I need the stock HD to follow this tutorial?
Because I dont have the original HDs, I only have the case.
So can I pick any HD, and record a image into it?  Or without the original HDs I can only proceed with the use of UART cable?

**Comment by KL-Yang** [comment]
If you want stock firmware, follow this thread. 
http://mybookworld.wikidot.com/hacks-and-howto#toc2
Later you can try to play with the new kernel.

**Comment by ffloress** [comment]
Sorry, I am lost, all these tutorials are for the original HDs, they are "debricking" and preserving data.
The debrick bash script seems to grep for the "WD" word in the hd manufacturer....
I dont have the original HDs anymore,I need to install from scratch, scratch...
But thank you for your help :)

**Comment by KL-Yang** [comment]
you need do a little bit more research.
http://mybookworld.wikidot.com/mybook-live
->How to's 8. Completly bricked ->
http://mybookworld.wikidot.com/forum/t-317579/complitly-debricking-guide-draft#post-1025024
Read through the forum post, you can get everything you need to install stock firmware on a blank HD.
