### ISSUE TITLE
System unstable

### ISSUE THREAD

**Issue by ewaldc** [KL-Yang/mbl-linux-4.0#2]
Hello,
I installed the 4.1.5 and Debian Jessie per the instructions.  I verified that block size is 4K.  RAID 1 is also still active, like the original mbl.
All boots fine with no errors, but when transferring a large file (1GB) over gigabit ethernet, the system hangs.  The only place where I deviated from the instructions is that /dev/sda1 is ext3 while I think you recommended ext2.  While issues occured with network tests, it could be related to the SATA driver.
Maybe I should just do a disk write test to verify where the issue is.
My drive is a Seagate 4TB hybrid drive.
Any suggestions?
Thanks in advance!
Ewald

**Comment by ewaldc** [comment]
I reformatted sda1 to ext2 with 4K block size and redeployed everything just to be 100% sure.  Same issue.

**Comment by KL-Yang** [comment]
Hi Ewald,

I am using a WD Green 3TB with uptime of almost 3 month, the load is low but definitely transferred some file over 2GB. But I am on kernel 4.1.11 now. Could you post your fdisk -l /dev/sda or df -h?

Regards
KL

**Comment by ewaldc** [comment]
KL,
Thanks for your response.  I made huge progress, although I am not 100% what actually did it:
1. Used a 3A power supply (just to be sure as these new hybrid drives may have peaks in power usage).  That by itself was not enough as I got another hang...
2. swapoff + reformat swap space with 16KB block size (-s 16384) + swapon
3. Back to ext3 (even though it's mounted as ext2)
4. Reformat my sda4 (just to be sure, even though it said block size was 4K)
5. Destroyed sda2 file system as this was a RAID partition

And all seems stable:
1. time dd if=/dev/zero of=/mnt/data/null bs=1M count=4k --> 71.4MB/s (considering it write to file system versus raw disk)
2. time dd if=/dev/zero of=/tmp/null bs=1M count=4k --> between 98.5MB/s and 186MB/s
3. Your request

root@ETNas2:~#  fdisk -l /dev/sda

Disk /dev/sda: 3.7 TiB, 4000787030016 bytes, 7814037168 sectors
Units: sectors of 1 \* 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 7B5B8A9C-4087-40CE-B6DE-A0B610A42DC6

Device       Start        End    Sectors  Size Type
/dev/sda1  1032192    5031935    3999744  1.9G Linux RAID
/dev/sda2  5031936    9031679    3999744  1.9G Linux RAID
/dev/sda3    30720    1032191    1001472  489M Linux swap
/dev/sda4  9031680 7814035455 7805003776  3.6T Linux filesystem

Partition table entries are not in disk order.

**Comment by jilinls** [comment]
看你们说话好吃力啊 问下哪里有升级4.0的教程呢？谢谢

**Comment by jilinls** [comment]
Maybe I am walled , you know. So I cannot open your blog link.Sorry to trouble you.

**Comment by KL-Yang** [comment]
There is no tutorial in the blog. You can try to follow the README.
This is not a drop in replacement of stock firmware.
需要折腾.

**Comment by jilinls** [comment]
I know, I exactly love 折腾.I could test because I have two😁

**Comment by KL-Yang** [comment]
Let's close this issue and **start another issue** and discuss there in Chinese.
Github might have forward this discussion to ewaldc, and it's just pure noise for him.
If you are not afraid of Z-turn, I can try to walk you through the installation of Debian Jessie with new kernel as mini server.
