### ISSUE TITLE
Kernel Cross Compilation

### ISSUE THREAD

**Issue by martinhoefling** [KL-Yang/mbl-linux-4.0#3]
Hey @KL-Yang, thanks for your efforts on porting the patches to 4.0. Can you give some hints how to cross-compile the kernel for the mbl, i.e. if a softfloat toolchain is required or not? Or are you compiling _on device_?

**Comment by KL-Yang** [comment]
It was compiled on the device, and the speed seems quite acceptable.

**Comment by martinhoefling** [comment]
Hey @KL-Yang , I got it working with https://github.com/MyBookLive/kernel-4.0.x, cross compilation on my x86_64 machine using [crosstool-ng](http://crosstool-ng.org/).
