### ISSUE TITLE
In Chinese

### ISSUE THREAD

**Issue by jilinls** [KL-Yang/mbl-linux-4.0#4]
抱歉，打搅了。第一次接触这个平台，不太会用。这里的对话会被发现吧？或者我想问你常用的联系方式来交流。😁

**Comment by KL-Yang** [comment]
你按README里面的执行就可以了， 需要一台有sata接口的PC（不要试图装到usb硬盘盒里面，如果你不明白512B和4kB sector区别的话）
1.备份数据，2.下载google drive上的那个rootfs, 3.拆下硬盘，接到pc的sata接口上，把第一个分区格式化为ext2格式 4.把rootfs解压缩到第一个分区，5.装回硬盘，应该就能启动了

**Comment by jilinls** [comment]
1.谷歌被墙，有其他的下载方式吗(如果上传不易的话，我再想其他办法)
2.我有一块未被格式化的硬盘，要重做官方原厂系统后再进行格式化第二分区
   还是我用PC接一块未被格式化的硬盘，再接一块正常使用的硬盘，然后克隆其分区？
   或者你可以有更好的办法？
3.不知道你是否知道syncy，我折腾它想使用这个软件。之前折腾openwrt的路由器上很好用的一  
   款同步百度云的软件。不知道4.0上是否可以使用？
4.MBL可以安装其他的系统或者固件？

**Comment by KL-Yang** [comment]
晚上我传一个去百度云你再下载
任何硬盘，随便分区，把**第一个**分区格式化为**ext2**，然后把下载的rootfs解压缩上去就可以了
这个是powerpc架构的CPU，不知道你说的软件是否可用
我只是用nfs,samba,openvpn和transmission,其它的都没有试过,所有Debian ppc32架构的软件都可安装

**Comment by KL-Yang** [comment]
如果想重做原厂固件，看这个
http://mybookworld.wikidot.com/forum/t-317579/complitly-debricking-guide-draft#post-1025024
我的rootfs只是新版内核+原装Debian，其它所有软件服务都要自己另外安装

**Comment by jilinls** [comment]
OK，没问题。谢谢。😄 

准备学习编译适合这个的软件。主要就是需要Python，依赖pycurl之类的环境。
我自己再研究。

冒昧问下是国内的晚上还是？

**Comment by KL-Yang** [comment]
百度链接 http://pan.baidu.com/s/1dDVm1jj
你可以先试一下

**Comment by jilinls** [comment]
因为经常做win的系统 手头没有linux启动盘  刚弄了个 可是不常用 所以不会用命令分区...
结果按照原厂的教程分了区 然后再进入到winPE DiskGenius 然后就不会搞了 
能告诉我 怎么直接用linux启动盘命令分区吗 给系统区要划分多大空间 或者只要一个ext2区可以吗

**Comment by jilinls** [comment]
现在我的硬盘情况就是 原厂的4个区

**Comment by KL-Yang** [comment]
随便分，第一个分区大于1GB左右就可以，格式化为ext2
