### ISSUE TITLE
Not including DM_CRYPT per default

### ISSUE THREAD

**Issue by berlincount** [KL-Yang/mbl-linux-4.0#5]
... althought that's extremely useful ;)

I'll go and compile my own kernel once more.

**Comment by KL-Yang** [comment]
Update the configuration and compiled latest 4.1.36 kernel, links updated in README.
The /boot/resource in the rootfs has script to allow boot into two different partitions.
I configured my MBL with sda1 as develop environment, and sda2 as normal NAS server.
copy /boot/resource/boot.scr_sda1 to /boot/boot.scr will boot into sda1, and similar to switch to sda2 as rootfs.
compile kernel locally on MBL is tolerable.
